[theme]
primaryColor = "#FF9900"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#F0F0F0"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true